#!/usr/bin/env bash

# This script accepts two arguments, domain and subdomain (optional),
# and displays information about the subdomain's DNS record.
# If only domain is provided, it displays information about the subdomains
# www, lb-01, web-01, and web-02.

# Disable SC2086 warning for echo statements with variables
# shellcheck disable=SC2086

display_dns_info() {
    local domain="$1"
    local subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        record_type=$(dig +short "$sub"."$domain" | awk '{print $2}')
        dest=$(dig +short "$sub"."$domain")
        echo "The subdomain $sub is a $record_type record and points to $dest"
    done
}

display_dns_info "$1" "$2"
