#!/bin/bash

domain="$1"
subdomain="$2"

if [[ -z "$subdomain" ]]; then
  # Display information for default subdomains
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  # Display information for specified subdomain
  subdomains=("$subdomain")
fi

for subdomain in "${subdomains[@]}"; do
  record=$(dig +short "$subdomain.$domain")
  if [[ -n "$record" ]]; then
    echo "The subdomain $subdomain.$domain is a $(dig +short -t "$record" "$subdomain.$domain") record and points to $record"
  else
    echo "The subdomain $subdomain.$domain does not exist"
  fi
done
